/**
 * Auto-generated by Dark Factory
 * Integration API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';


// GET - List all Integration records
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '20');
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      prisma.integration.findMany({
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
      }),
      prisma.integration.count(),
    ]);

    return NextResponse.json({
      data: items,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    });
  } catch (error) {
    console.error('Error fetching Integration:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Integration records' },
      { status: 500 }
    );
  }
}


// POST - Create a new Integration
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // Validate required fields
    const required = ['name', 'type'];
    const missing = required.filter(field => !(field in body));
    if (missing.length > 0) {
      return NextResponse.json(
        { error: `Missing required fields: ${missing.join(', ')}` },
        { status: 400 }
      );
    }

    const integration = await prisma.integration.create({
      data: body,
    });

    return NextResponse.json(integration, { status: 201 });
  } catch (error) {
    console.error('Error creating Integration:', error);
    return NextResponse.json(
      { error: 'Failed to create Integration' },
      { status: 500 }
    );
  }
}
