/**
 * Auto-generated by Dark Factory
 * TaskDependency Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single TaskDependency by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const taskDependency = await prisma.taskDependency.findUnique({
      where: { id },
    });

    if (!taskDependency) {
      return NextResponse.json(
        { error: 'TaskDependency not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(taskDependency);
  } catch (error) {
    console.error('Error fetching TaskDependency:', error);
    return NextResponse.json(
      { error: 'Failed to fetch TaskDependency' },
      { status: 500 }
    );
  }
}


// PUT - Update a TaskDependency
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const taskDependency = await prisma.taskDependency.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(taskDependency);
  } catch (error) {
    console.error('Error updating TaskDependency:', error);
    return NextResponse.json(
      { error: 'Failed to update TaskDependency' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a TaskDependency
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.taskDependency.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting TaskDependency:', error);
    return NextResponse.json(
      { error: 'Failed to delete TaskDependency' },
      { status: 500 }
    );
  }
}
