/**
 * Auto-generated by Dark Factory
 * TelegramChatHistory Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single TelegramChatHistory by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const telegramChatHistory = await prisma.telegramChatHistory.findUnique({
      where: { id },
    });

    if (!telegramChatHistory) {
      return NextResponse.json(
        { error: 'TelegramChatHistory not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(telegramChatHistory);
  } catch (error) {
    console.error('Error fetching TelegramChatHistory:', error);
    return NextResponse.json(
      { error: 'Failed to fetch TelegramChatHistory' },
      { status: 500 }
    );
  }
}


// PUT - Update a TelegramChatHistory
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const telegramChatHistory = await prisma.telegramChatHistory.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(telegramChatHistory);
  } catch (error) {
    console.error('Error updating TelegramChatHistory:', error);
    return NextResponse.json(
      { error: 'Failed to update TelegramChatHistory' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a TelegramChatHistory
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.telegramChatHistory.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting TelegramChatHistory:', error);
    return NextResponse.json(
      { error: 'Failed to delete TelegramChatHistory' },
      { status: 500 }
    );
  }
}
