/**
 * Auto-generated by Dark Factory
 * AuditLog Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single AuditLog by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const auditLog = await prisma.auditLog.findUnique({
      where: { id },
    });

    if (!auditLog) {
      return NextResponse.json(
        { error: 'AuditLog not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(auditLog);
  } catch (error) {
    console.error('Error fetching AuditLog:', error);
    return NextResponse.json(
      { error: 'Failed to fetch AuditLog' },
      { status: 500 }
    );
  }
}


// PUT - Update a AuditLog
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const auditLog = await prisma.auditLog.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(auditLog);
  } catch (error) {
    console.error('Error updating AuditLog:', error);
    return NextResponse.json(
      { error: 'Failed to update AuditLog' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a AuditLog
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.auditLog.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting AuditLog:', error);
    return NextResponse.json(
      { error: 'Failed to delete AuditLog' },
      { status: 500 }
    );
  }
}
