/**
 * Auto-generated by Dark Factory
 * Entity API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';


// POST - Create a new Entity
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    

    const entity = await prisma.entity.create({
      data: body,
    });

    return NextResponse.json(entity, { status: 201 });
  } catch (error) {
    console.error('Error creating Entity:', error);
    return NextResponse.json(
      { error: 'Failed to create Entity' },
      { status: 500 }
    );
  }
}
