/**
 * Auto-generated by Dark Factory
 * Event Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single Event by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const event = await prisma.event.findUnique({
      where: { id },
    });

    if (!event) {
      return NextResponse.json(
        { error: 'Event not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(event);
  } catch (error) {
    console.error('Error fetching Event:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Event' },
      { status: 500 }
    );
  }
}


// PUT - Update a Event
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const event = await prisma.event.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(event);
  } catch (error) {
    console.error('Error updating Event:', error);
    return NextResponse.json(
      { error: 'Failed to update Event' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a Event
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.event.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Event:', error);
    return NextResponse.json(
      { error: 'Failed to delete Event' },
      { status: 500 }
    );
  }
}
