/**
 * Auto-generated by Dark Factory
 * Workflow Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single Workflow by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const workflow = await prisma.workflow.findUnique({
      where: { id },
    });

    if (!workflow) {
      return NextResponse.json(
        { error: 'Workflow not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(workflow);
  } catch (error) {
    console.error('Error fetching Workflow:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Workflow' },
      { status: 500 }
    );
  }
}


// PUT - Update a Workflow
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const workflow = await prisma.workflow.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(workflow);
  } catch (error) {
    console.error('Error updating Workflow:', error);
    return NextResponse.json(
      { error: 'Failed to update Workflow' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a Workflow
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.workflow.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Workflow:', error);
    return NextResponse.json(
      { error: 'Failed to delete Workflow' },
      { status: 500 }
    );
  }
}
