/**
 * Auto-generated by Dark Factory
 * Subscription Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single Subscription by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const subscription = await prisma.subscription.findUnique({
      where: { id },
    });

    if (!subscription) {
      return NextResponse.json(
        { error: 'Subscription not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(subscription);
  } catch (error) {
    console.error('Error fetching Subscription:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Subscription' },
      { status: 500 }
    );
  }
}


// PUT - Update a Subscription
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const subscription = await prisma.subscription.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(subscription);
  } catch (error) {
    console.error('Error updating Subscription:', error);
    return NextResponse.json(
      { error: 'Failed to update Subscription' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a Subscription
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.subscription.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Subscription:', error);
    return NextResponse.json(
      { error: 'Failed to delete Subscription' },
      { status: 500 }
    );
  }
}
