/**
 * Auto-generated by Dark Factory - Cleaned
 */

// Agent Template Types
export interface AgentTemplateInput {
  name: string;
  description: string;
  type: string;
  capabilities: unknown[];
  personalityConfig: Record<string, unknown>;
  defaultConfig?: Record<string, unknown>;
}

// Workflow Types
export interface WorkflowInput {
  name: string;
  description?: string;
  trigger: Record<string, unknown>;
  steps?: unknown[];
}

// Task Types
export interface TaskInput {
  type: string;
  agentId: string;
  input?: Record<string, unknown>;
  priority?: number;
}
