/**
 * Auto-generated by Dark Factory
 * Integration Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single Integration by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const integration = await prisma.integration.findUnique({
      where: { id },
    });

    if (!integration) {
      return NextResponse.json(
        { error: 'Integration not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(integration);
  } catch (error) {
    console.error('Error fetching Integration:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Integration' },
      { status: 500 }
    );
  }
}


// PUT - Update a Integration
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const integration = await prisma.integration.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(integration);
  } catch (error) {
    console.error('Error updating Integration:', error);
    return NextResponse.json(
      { error: 'Failed to update Integration' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a Integration
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.integration.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Integration:', error);
    return NextResponse.json(
      { error: 'Failed to delete Integration' },
      { status: 500 }
    );
  }
}
