/**
 * Auto-generated by Dark Factory
 * Agent Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single Agent by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const agent = await prisma.agent.findUnique({
      where: { id },
    });

    if (!agent) {
      return NextResponse.json(
        { error: 'Agent not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(agent);
  } catch (error) {
    console.error('Error fetching Agent:', error);
    return NextResponse.json(
      { error: 'Failed to fetch Agent' },
      { status: 500 }
    );
  }
}


// PUT - Update a Agent
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const agent = await prisma.agent.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(agent);
  } catch (error) {
    console.error('Error updating Agent:', error);
    return NextResponse.json(
      { error: 'Failed to update Agent' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a Agent
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.agent.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting Agent:', error);
    return NextResponse.json(
      { error: 'Failed to delete Agent' },
      { status: 500 }
    );
  }
}
