/**
 * Auto-generated by Dark Factory
 * KnowledgeNode Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single KnowledgeNode by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const knowledgeNode = await prisma.knowledgeNode.findUnique({
      where: { id },
    });

    if (!knowledgeNode) {
      return NextResponse.json(
        { error: 'KnowledgeNode not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(knowledgeNode);
  } catch (error) {
    console.error('Error fetching KnowledgeNode:', error);
    return NextResponse.json(
      { error: 'Failed to fetch KnowledgeNode' },
      { status: 500 }
    );
  }
}


// PUT - Update a KnowledgeNode
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const knowledgeNode = await prisma.knowledgeNode.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(knowledgeNode);
  } catch (error) {
    console.error('Error updating KnowledgeNode:', error);
    return NextResponse.json(
      { error: 'Failed to update KnowledgeNode' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a KnowledgeNode
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.knowledgeNode.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting KnowledgeNode:', error);
    return NextResponse.json(
      { error: 'Failed to delete KnowledgeNode' },
      { status: 500 }
    );
  }
}
