/**
 * Auto-generated by Dark Factory
 * AgentTemplate Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single AgentTemplate by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const agentTemplate = await prisma.agentTemplate.findUnique({
      where: { id },
    });

    if (!agentTemplate) {
      return NextResponse.json(
        { error: 'AgentTemplate not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(agentTemplate);
  } catch (error) {
    console.error('Error fetching AgentTemplate:', error);
    return NextResponse.json(
      { error: 'Failed to fetch AgentTemplate' },
      { status: 500 }
    );
  }
}


// PUT - Update a AgentTemplate
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const agentTemplate = await prisma.agentTemplate.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(agentTemplate);
  } catch (error) {
    console.error('Error updating AgentTemplate:', error);
    return NextResponse.json(
      { error: 'Failed to update AgentTemplate' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a AgentTemplate
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.agentTemplate.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting AgentTemplate:', error);
    return NextResponse.json(
      { error: 'Failed to delete AgentTemplate' },
      { status: 500 }
    );
  }
}
