/**
 * Auto-generated by Dark Factory
 * WorkflowStep Dynamic API Routes
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}


// GET - Get a single WorkflowStep by ID
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const workflowStep = await prisma.workflowStep.findUnique({
      where: { id },
    });

    if (!workflowStep) {
      return NextResponse.json(
        { error: 'WorkflowStep not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(workflowStep);
  } catch (error) {
    console.error('Error fetching WorkflowStep:', error);
    return NextResponse.json(
      { error: 'Failed to fetch WorkflowStep' },
      { status: 500 }
    );
  }
}


// PUT - Update a WorkflowStep
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    // Remove fields that shouldn't be updated
    delete body.id;
    delete body.createdAt;
    delete body.updatedAt;

    const workflowStep = await prisma.workflowStep.update({
      where: { id },
      data: body,
    });

    return NextResponse.json(workflowStep);
  } catch (error) {
    console.error('Error updating WorkflowStep:', error);
    return NextResponse.json(
      { error: 'Failed to update WorkflowStep' },
      { status: 500 }
    );
  }
}


// DELETE - Delete a WorkflowStep
export async function DELETE(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    await prisma.workflowStep.delete({
      where: { id },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting WorkflowStep:', error);
    return NextResponse.json(
      { error: 'Failed to delete WorkflowStep' },
      { status: 500 }
    );
  }
}
